version: '2'
services:
    instagram-app:
        image: instagram
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://instagram-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=instagram
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=instagram-elasticsearch:9300
        ports:
            - 8080:8080
    instagram-mongodb:
        extends:
            file: mongodb.yml
            service: instagram-mongodb
    instagram-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: instagram-elasticsearch
